### PR TITLE
Checkout full repo

### PR DESCRIPTION
**Pull request by pitermarx**

### CODE REVIEW

**Comment by devlead** [comment]
@pitermarx thanks for your contribution :+1:  could you please add an test case for the two scenarios in [test.cake](https://github.com/WCOMAB/Cake_Git/blob/master/test.cake), so it's tested in the xplat integration tests.

**Comment by pitermarx** [comment]
I was wondering where the tests were...
Didn't think they would be written in Cake itself!
:+1:

**Comment by pitermarx** [comment]
I added a simple test.
For more complex tests the CakeGitTestRepo would have to have more branches

**Comment by devlead** [comment]
@pitermarx great, could you please squash/rebase into 1 commit.

**Comment by pitermarx** [comment]
I think I did it!

**Comment by pitermarx** [comment]
Is there a problem with travis or did I do something wrong?

**Comment by devlead** [comment]
@pitermarx travis had issues yesterday
https://www.traviscistatus.com/incidents/rqb906yypnk0

But I restarted the build hopefully issues are no w solved and it completes.

**Comment by pitermarx** [comment]
any developments on this?

**Comment by devlead** [comment]
@pitermarx Travis now succesed, LGTM! Merged :+1:

**Comment by devlead** [comment]
@pitermarx  [Cake.Git 0.5.0](https://www.nuget.org/packages/Cake.Git/0.5.0) now published.

**Comment by pitermarx** [comment]
Awesome

--
Pedro Marques

No dia 01/07/2016, às 12:40, Mattias Karlsson <notifications@github.com> escreveu:

**Pull request merged**
