### PR TITLE
Add alias for git push with refspec

### PR DESCRIPTION
**Pull request by IanMercer**
This PR adds two aliases for pushing with a refspec which is needed in order to tag a remote.

Usage example:
    GitTag("./", "v1.0.0");
    GitPushRef("./", gitUsername, gitPassword, "origin", "v1.0.0");

[Fixes: https://github.com/WCOMAB/Cake_Git/issues/9]

### CODE REVIEW

**Comment by devlead** [comment]
@IanMercer thanks for contributing :+1: 
* Please add tests to [test.cake](https://github.com/WCOMAB/Cake_Git/blob/master/test.cake) so we know it works xplat and can catch any regressions
* See you update LibGit2Sharp and looks like Repository Check out is obsoleted which fails the build, correct the checkout option or revert the upgrade.
```
GitAliases.Checkout.cs(63,46): error CS0618: Warning as Error: `LibGit2Sharp.Repository.Checkout(string, LibGit2Sharp.CheckoutOptions)' is obsolete: `This method is deprecated. Please use LibGit2Sharp.Commands.Checkout()'
```

**Comment by IanMercer** [comment]
Fixed the warning message.  Not sure how to proceed with the test:
1. There doesn't seem to be a test for `Git-Push` to model this on.
2. Trying a local push gets the error "Error: Local push doesn't (yet) support pushing to non-bare repos."
3. To get round this I tried creating a new bare repo to push to but then I hit the issue that there is no alias in Cake-Git to add a remote.

What am I missing?

**Comment by devlead** [comment]
Does it work if you clone a local repo to a new local path, change something and push that?

**Comment by IanMercer** [comment]
No, tried that, gets the error message "Error: Local push doesn't (yet) support pushing to non-bare repos". So then I tried creating a third, bare repo and pushing to that; but without a command to add a remote that's not possible either.

**Comment by devlead** [comment]
I see, could you rebase into 1 commit and I'll do a final review before merging.

**Comment by IanMercer** [comment]
OK, will do. 
BTW see also: https://help.github.com/articles/about-pull-request-merge-squashing/

**Comment by IanMercer** [comment]
I left three commits because two are really not about this feature. Your choice.

**Comment by devlead** [comment]
@IanMercer your changed have now been merged, thanks for contributing :+1: 
Version [0.8.0](https://www.nuget.org/packages/Cake.Git/0.8.0) is now pushed to NuGet.org and should be avail shortly.

**Pull request merged**
